pyconweb2022/pyconemailer/admin.py, pyconweb2022/pyconemailer/apps.py, pyconweb2022/pyconemailer/models.py, pyconweb2022/pyconemailer/tests.py, pyconweb2022/pyconemailer/views.py, pyconweb2022/pytest.ini, requirements.txt
* pytest 셋업
* requirementst.txt 설정
=> Pytest init

.github/workflows/run_test.yml, pyconweb2022/pyconemailer/tests.py, requirements.txt
- fix missing dependency
- add github workflow to run pytest
=> add GitHub action

.github/workflows/run_test.yml
- fixed `pull_requests` to `pull_request`
- add installing `mysql-common`
=> fix typo in github action test

.github/workflows/run_test.yml, README.md, pyconweb2022/manage.py, pyconweb2022/program/apps.py, pyconweb2022/pyconemailer/apps.py, pyconweb2022/pyconemailer/migrations/0001_initial.py, pyconweb2022/pyconemailer/tests.py, pyconweb2022/pyconemailer/urls.py, pyconweb2022/pyconemailer/views.py, pyconweb2022/pyconweb2022/asgi.py, pyconweb2022/pyconweb2022/settings.py, pyconweb2022/pyconweb2022/settings_prod.py, pyconweb2022/pyconweb2022/urls.py, pyconweb2022/pyconweb2022/wsgi.py, pyconweb2022/sponsor/admin.py, pyconweb2022/sponsor/apps.py, pyconweb2022/sponsor/models.py, pyconweb2022/sponsor/routers.py, pyconweb2022/sponsor/serializers.py, pyconweb2022/sponsor/viewsets.py
this PR will adopt lint with `black`  by [github action](https://black.readthedocs.io/en/stable/integrations/github_actions.html)
=> apply black in PR workflow for python lint

.github/PULL_REQUEST_TEMPLATE.md
=> add PR Template

pyconweb2022/pyconemailer/viewsets.py, pyconweb2022/pyconweb2022/urls.py
후원사 메일링 기능 선오픈을 위해 메일링 API 권한체크를 우회하도록 수정
모든 API의 prefix에 `/api` 추가
Thank you ❤️
=> 후원사 메일링 기능 선오픈을 위해 메일링 API 권한체크를 우회하도록 수정

.github/workflows/front_deploy.yml, frontend/next.config.js, frontend/package-lock.json, frontend/package.json, frontend/serverless.yml
=> Serverless 프레임워크 적용

frontend/components/layout/Layout.tsx, frontend/package.json, frontend/pages/_app.tsx, frontend/yarn.lock
title, url에 대한 SEO부터 추가했습니다.
이후 og 업데이트가 필요합니다.
Thank you ❤️
=> 페이지 SEO 추가

pyconweb2022/content/serializers.py, pyconweb2022/news/serializers.py
`dangerouslySetInnerHTML`를 사용하지 않기 위해 마크다운을 HTML로 렌더링 하지 않고 직접 반환하도록 수정
Thank you ❤️
=> 마크다운을 HTML로 렌더링 하지 않고 직접 반환하도록 수정

frontend/assets/styles/markdown.ts, frontend/assets/styles/theme.ts, frontend/components/core/MarkdownLinks.tsx, frontend/data/enums/PageName.ts, frontend/locales/en/pageTitle.ts, frontend/locales/ko/pageTitle.ts, frontend/pages/api/contribute.ts, frontend/pages/contribute/cfp/guide.tsx, frontend/pages/contribute/cfp/index.tsx, frontend/routes/routes.ts
- CFP 신청 페이지, CFP 가이드 페이지 추가
Thank you ❤️
=> 기여하기 > CFP 페이지 생성

pyconweb2022/pyconweb2022/settings_prod.py
`Character set '255' unsupported` 오류가 다시 발생함에 따라 변경한 설정 롤백
Thank you ❤️
=> `Character set '255' unsupported` 오류가 다시 발생함에 따라 변경한 설정 롤백

pyconweb2022/pyconweb2022/settings_prod.py
`Character set '255' unsupported` 오류가 다시 발생함에 따라 변경한 설정 롤백
Thank you ❤️
=> (코드 포멧 수정)`Character set '255' unsupported` 오류가 다시 발생함에 따라 변경한 설정 롤백

.github/workflows/front_deploy_on_dev.yml, frontend/package.json, pyconweb2022/program/viewsets.py, pyconweb2022/sponsor/viewsets.py
Viewset에서 상속받는 Parent 수정 및 DEV 배포 중 발생하는 오류 수정
* 의존성 누락으로 인한 오류
* `PROD`와 `DEV` 스테이지 간 의존성 차이가 꽤 있는 것을 발견
* 스테이지 간 의존성 동기화 (PROD -> DEV 로 복사)
Thank you ❤️
=> Viewset에서 상속받는 Parent 수정 및 DEV 배포 중 발생하는 오류 수정

frontend/package.json
`typescript` 의존성을 추가합니다.
Thank you ❤️
=> DEV 배포 중 발생하는 오류 해결 (의존성 추가)

pyconweb2022/pyconweb2022/settings.py, pyconweb2022/pyconweb2022/urls.py, requirements.txt
=> add swagger using drf-spectacular

pyconweb2022/pyconweb2022/settings.py
=> Update: make_aware expects a naive datetime 오류 수정

pyconweb2022/content/admin.py, pyconweb2022/content/resources.py, pyconweb2022/news/admin.py, pyconweb2022/news/resources.py, pyconweb2022/program/admin.py, pyconweb2022/program/resources.py, pyconweb2022/pyconweb2022/settings.py
DB 레코드 덤프를 위한 `import-export` 모듈을 추가합니다.
Thank you ❤️
=> Import export module 추가

pyconweb2022/content/serializers.py
없어져버린 `eng_content` 복구합니다.
Thank you ❤️
=> Fix: 없어져버린 `eng_content` 복구

pyconweb2022/pyconweb2022/customBoto3Storage.py, pyconweb2022/pyconweb2022/settings.py
#84 이슈를 해결합니다.
S3에 접근 불가능으로 발생하는 `timeout` 이슈와,
Zappa 로 배포한 lambda에서 S3를 정적/미디어 저장소로 사용할때 발생하는 `invalid token` 이슈를 해결합니다.
Thank you ❤️
=> Fix: 파일 업로드 불가능 이슈 수정

pyconweb2022/pyconweb2022/customBoto3Storage.py, pyconweb2022/pyconweb2022/settings.py
#84 이슈와, 롤백된 `eng_content` 필드를 복원합니다.
Thank you ❤️
=> Fix: 이미지 업로드 불가능 오류 해결

pyconweb2022/program/tests.py, pyconweb2022/program/viewsets.py
=> Hotfix: accept를 조회조건으로 변경

pyconweb2022/program/serializers.py
=> Update: 프로그램에 ID필드 추가

pyconweb2022/program/serializers.py, pyconweb2022/program/tests.py, pyconweb2022/sponsor/serializers.py
Update: 후원사, 세션 API에 ID 필드 추가
Thank you ❤️
=> Update: 후원사, 세션 API에 ID 필드 추가

pyconweb2022/sponsor/serializers.py, pyconweb2022/sponsor/viewsets.py
=> Hotfix: 잘못 지정한 serializer 명칭 수정

pyconweb2022/program/admin.py, pyconweb2022/program/routers.py, pyconweb2022/program/viewsets.py
카테고리 별로 조회할 수 있는 API 작성
Thank you ❤️
=> 카테고리 별로 조회할 수 있는 API 작성

pyconweb2022/program/admin.py, pyconweb2022/program/routers.py, pyconweb2022/program/viewsets.py
카테고리별 조회기능만 별도로 선배포
Thank you ❤️
=> 카테고리별 조회기능만 별도로 선배포

frontend/locales/ko/sponsorLevel.ts
=> 후원사 등급 파트너A의 명칭을 파트너로 변경

frontend/locales/en/sponsorLevel.ts, frontend/locales/ko/sponsorLevel.ts
Update: 파트너A 등급명을 파트너로 변경 (영문)
Thank you ❤️
=> Update: 파트너A 등급명을 파트너로 변경 (영문)

frontend/locales/en/sponsorLevel.ts, frontend/locales/ko/sponsorLevel.ts
=> 후원사 등급 명칭 변경 반영

frontend/locales/en/sponsorLevel.ts, frontend/locales/ko/sponsorLevel.ts, pyconweb2022/sponsor/viewsets.py
=> 후원사 이름순 정렬

frontend/components/service/Program/TalkTable.tsx, frontend/pages/program/talk-schedule.tsx
=> 세션 시간표 정렬 적용

frontend/components/service/Program/TalkTable.tsx, frontend/components/service/Sponsor/SponsorList.tsx
=> 키스톤 디자인 수정

frontend/pages/program/talk-schedule.tsx
=> 세션 유튜브 링크 추가

frontend/components/service/Home/PersonListItem.tsx, frontend/components/service/PreviousPyconkr/PreviousPyconkrList.tsx, frontend/components/service/Program/Speaker.tsx, frontend/data/constants/staff.ts, frontend/data/enums/PageName.ts, frontend/interfaces/IProgram.ts, frontend/locales/en/label.ts, frontend/locales/en/pageTitle.ts, frontend/locales/ko/label.ts, frontend/locales/ko/pageTitle.ts, frontend/pages/about/organizing-team.tsx, frontend/pages/program/talks/[id].tsx, frontend/routes/routes.ts
=> 파이콘 한국 준비위원회 페이지 추가

frontend/components/service/Home/PersonListItem.tsx, frontend/components/service/PreviousPyconkr/PreviousPyconkrList.tsx, frontend/components/service/Program/Speaker.tsx, frontend/data/constants/staff.ts, frontend/data/enums/PageName.ts, frontend/interfaces/IProgram.ts, frontend/locales/en/label.ts, frontend/locales/en/pageTitle.ts, frontend/locales/ko/label.ts, frontend/locales/ko/pageTitle.ts, frontend/pages/about/organizing-team.tsx, frontend/pages/program/talk-schedule.tsx, frontend/pages/program/talks/[id].tsx, frontend/routes/routes.ts
=> 발표 영상 섹션 추가 및 트랙 영상 링크 제거

frontend/data/constants/staff.ts, frontend/pages/program/talks/[id].tsx
=> 영상 링크 및 파준위 소개 업데이트

pyconweb2022/sponsor/viewsets.py
파이콘 한국 2022의 모든 개인후원 금액을 동일 -> 기존의 금액순 정렬 룰이 무의미하기에, 셔플 후 응답
feature: 개인후원자 순서를 랜덤하게 응답
Thank you ❤️
=> feature: 개인후원자 순서를 랜덤하게 응답
